-- AlterTable
ALTER TABLE "Assumption" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Issue" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Result" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "ResultError" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Spec" ALTER COLUMN "id" DROP DEFAULT;
