const COGNITO_USER_POOL_ID = process.env.COGNITO_USER_POOL_ID ?? "";
const COGNITO_CLIENT_ID = process.env.COGNITO_CLIENT_ID ?? "";
const COGNITO_POOL_REGION = process.env.COGNITO_POOL_REGION ?? "";

if (!COGNITO_USER_POOL_ID || !COGNITO_CLIENT_ID || !COGNITO_POOL_REGION) {
  throw new Error(
    "COGNITO_USER_POOL_ID, COGNITO_CLIENT_ID, and COGNITO_POOL_REGION must be set",
  );
}

export { COGNITO_USER_POOL_ID, COGNITO_CLIENT_ID, COGNITO_POOL_REGION };
